group:
  newbie:
    pitch: 1
    sound: chicken
    volume: 1
  admin:
    pitch: -1
    sound: chicken
    volume: 1
user:
  ccc54a6c-1c87-4064-a299-90857fb16a5c:
    sound: chicken
    volume: 0
    pitch: 1
sounds:
  chicken: chicken_idle
  orb: orb_pickup
